name: Selenium with jUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
    # Optional: do not specify to match Chrome's version
        chromedriver-version: '117'
    
    - name: Run tests with Maven
      run: mvn -B clean test
