name: Selenium with jUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@v1
    with:
      chrome-version: 117.0.5938.92
    id: setup-chrome
     - run:|
      echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
      ${{ steps.setup-chrome.outputs.chrome-path }} --version

    
    - name: Run tests with Maven
      run: mvn -B clean test
